name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macOS-12
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        
        with:
          deno-version: "1.34.1"

      - name: Run fmt
        run: |
          deno fmt --check

      - name: Run lint
        run: |
          deno lint

      - name: Check main.ts
        run: |
          deno check main.ts
          
      - name: Run tests
        run: |
          deno test -A